sdkversion: 3.3.3
name: SystemTest
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.1
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.systemtest
  BundleURLScheme: systemtest
wp:
  productid: '160ec730-bc4d-012f-2a5a-1040f37b2b30'
symbian:
  uid: '0xe1d980d4'
android:
  version: 2.3.3

extensions: ["json", "another-extension"]
